---
title: "Pipeline Comparison"
author: "Daniel Munro"
date: "7/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
```

I'm comparing TensorQTL without covariates, with covariates, and R/qtl2. The covariates are:

- 15 PEER factors (number chosen based on rough guidelines)
- 8 factors for genetic similarity to each of the founder strains

```{r}
eqtls <- read_tsv("data/eqtls.txt", col_types = "ccciidddd") %>%
    filter(qval < 0.05) %>%
    mutate(
        # label = fct_recode(
        #     method,
        #     "TensorQTL, no covariates, raw" = "basic",
        #     "TensorQTL, no covariates, TPM" = "basic3",
        #     "TensorQTL, no covariates, TMM/raw" = "basic4",
        #     "TensorQTL, covariates, raw" = "main",
        #     "TensorQTL, covariates, TPM" = "main3",
        #     "TensorQTL, covariates, TMM/raw" = "main4",
        #     "R/qtl2" = "qtl2"
        # ),
        expression = fct_collapse(
            method,
            "Read counts" = c("basic", "main", "qtl2"),
            "TPM" = c("basic3", "main3"),
            "TMM" = c("basic4", "main4"),
        ),
        covar = fct_collapse(
            method,
            "without covariates" = c("basic", "basic3", "basic4"),
            "with covariates" = c("main", "main3", "main4", "qtl2"),
        ),
        label = str_c(expression, " ", covar)
    ) %>%
    filter(method != "qtl2")
```

```{r fig.width=8, fig.height=6}
counts <- eqtls %>%
    group_by(expression, covar) %>%
    summarise(n_eQTLs = n(),
              n_eQTLs_with_ASE = sum(!is.na(log2_aFC_ASE)),
              .groups = "drop")

corrs <- eqtls %>%
    filter(!is.na(log2_aFC_ASE) & !is.na(log2_aFC_eQTL)) %>%
    group_by(expression, covar) %>%
    summarise(
        R = cor(log2_aFC_ASE, log2_aFC_eQTL),
        rho = cor(log2_aFC_ASE, log2_aFC_eQTL, method = "s"),
        beta = deming::deming(log2_aFC_eQTL ~ log2_aFC_ASE)$coefficients[2],
        .groups = "drop"
    ) %>%
    left_join(counts, by = c("expression", "covar")) %>%
    mutate(
        stats = str_c("R=", format(R, digits = 2),
                      " rho=", format(rho, digits = 2),
                      " β=", format(beta, digits = 2)),
        count = str_glue("n = {n_eQTLs} ({n_eQTLs_with_ASE})")
    )
eqtls %>%
    filter(!is.na(log2_aFC_ASE) & !is.na(log2_aFC_eQTL)) %>%
    ggplot(aes(x = log2_aFC_ASE, y = log2_aFC_eQTL)) +
    # facet_wrap(~ label) +
    facet_grid(rows = vars(covar), cols = vars(expression)) +
    geom_point(size = 0.25, alpha = 0.5) +
    geom_text(aes(x = -7.8, y = 7.8, label = stats), data = corrs, hjust = "left") +
    geom_text(aes(x = -7.8, y = 6, label = count), data = corrs, hjust = "left") +
    expand_limits(x = c(-8, 8), y = c(-8, 8)) +
    theme_minimal() +
    xlab("log2 aFC (ASE)") +
    ylab("log2 aFC (eQTLs)") +
    ggtitle("aFC correlations for eQTLs in eye tissue")

# ggsave("pipeline_comparison.png", width = 7.5, height = 5.5)
```
